doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_mapping: false

        mappings:
            User:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/User/Domain/Entity'
                prefix: 'App\User\Domain\Entity'