parameters:

services:
    _defaults:
        autowire: true     
        autoconfigure: true
    App\:
        resource: '../src/'
    App\User\Domain\Repository\UserRepositoryInterface:
        alias: App\User\Infrastructure\Repository\UserRepository
